-- Which categories contribute the most to the overall sales?
WITH category_sales AS (
SELECT 
	category,
	SUM(sales_amount) total_sales 
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p 
ON p.product_key = f.product_key
GROUP BY category)

SELECT
	category,
	total_sales,
	SUM(total_sales) OVER () overall_sales,
	CONCAT(ROUND((CAST(total_sales AS FLOAT) / SUM(total_sales) OVER ()) * 100, 2), '%')  AS percentage_of_total
FROM category_sales
ORDER BY total_sales DESC;

  
-- Sales amount generated by each client and how an individual client
-- colaborates with our business (part-to-whole)
-- Which customers contribute the most to the overall sales?
WITH customer_sales AS (
	SELECT
		customer_key,
		SUM(sales_amount) AS total_sales_by_customer
	FROM gold.fact_sales
	GROUP BY customer_key
)

SELECT 
	cs.customer_key,
	CONCAT(c.first_name, ' ', c.last_name) AS full_name,
	total_sales_by_customer,
	SUM(total_sales_by_customer) OVER () AS total_sales,
	CONCAT(ROUND(CAST(total_sales_by_customer AS FLOAT) / SUM(total_sales_by_customer) OVER () * 100, 2), '%') AS percentage_of_total
FROM customer_sales cs
LEFT JOIN gold.dim_customers c
ON cs.customer_key = c.customer_key
ORDER BY total_sales_by_customer DESC;


-- Quantity of products utilized by product line
-- Which product lines has the highest quantity of products?
WITH quantity_by_line AS (
	SELECT 
		p.product_line,
		SUM(quantity) quantity_per_line
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.product_line
)

SELECT 
	product_line,
	quantity_per_line,
	SUM(quantity_per_line) OVER () total_quantity_of_lines,
	CONCAT(ROUND(CAST(quantity_per_line AS FLOAT) / SUM(quantity_per_line) OVER () * 100, 2), '%') AS percentage_of_total
FROM quantity_by_line
ORDER BY quantity_per_line DESC;
