-- Find the total number of customers by countries
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find the total customers by gender
SELECT 
	gender,
	COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find the total customers by marital status
SELECT
	marital_status,
	COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY marital_status;

-- Find total products by category
SELECT
	category,
	COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT 
	category,
	AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
-- I usually start with the Fact, then LEFT JOIN
-- the dimensions to it
SELECT
	p.category,
	SUM(fs.sales_amount) total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products p
ON p.product_key = fs.product_key
GROUP BY p.category 
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(fs.sales_amount) total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers c
ON c.customer_key = fs.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name 
ORDER BY total_revenue DESC;

-- What is the distribution of items sold across countries?
SELECT 
	c.country,
	SUM(fs.quantity) total_items
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers c
ON c.customer_key = fs.customer_key
GROUP BY c.country 
ORDER BY total_items DESC;

